/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_jxfn_jxfn_jni_test */

#ifndef _Included_edu_jxfn_jxfn_jni_test
#define _Included_edu_jxfn_jxfn_jni_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_jxfn_jxfn_jni_test
 * Method:    JniHelloWorld
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_edu_jxfn_jxfn_jni_1test_JniHelloWorld
  (JNIEnv * env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
