/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_jxfn_jxfn_PreProcess */

#ifndef _Included_edu_jxfn_jxfn_PreProcess
#define _Included_edu_jxfn_jxfn_PreProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_jxfn_jxfn_PreProcess
 * Method:    preProcess
 * Signature: ([I)[I
 */
JNIEXPORT jstring JNICALL Java_edu_jxfn_jxfn_PreProcess_preProcess
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
